---
name: Lint

on:
  pull_request:
    paths:
      - "secjson/**/**"

jobs:
  build:
    name: JSON lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Check JSON files
        run: .github/json_check.sh secjson
